# Generated by Django 5.0.3 on 2024-03-25 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetracking_app.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetracking_app.person'),
        ),
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=64, unique=True)),
                ('department', models.ManyToManyField(to='timetracking_app.department')),
                ('employee', models.ManyToManyField(to='timetracking_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='LoggedHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.FloatField()),
                ('employee', models.ManyToManyField(to='timetracking_app.person')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetracking_app.saleschannel')),
            ],
        ),
    ]
