# Generated by Django 5.0.3 on 2024-03-26 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking_app', '0002_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='persons_department', to='timetracking_app.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_manager', to='timetracking_app.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(),
        ),
    ]
