# Generated by Django 5.0.3 on 2024-04-04 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking_app', '0002_alter_person_options_alter_person_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedhours',
            name='department',
            field=models.ManyToManyField(to='timetracking_app.department'),
        ),
        migrations.AlterField(
            model_name='loggedhours',
            name='hour',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.25), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
