# Generated by Django 5.0.3 on 2024-03-26 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking_app', '0003_person_department_alter_department_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons_department', to='timetracking_app.department'),
        ),
    ]
