# Generated by Django 5.0.3 on 2024-03-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking_app', '0004_alter_person_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedhours',
            name='date',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
    ]
