# Generated by Django 5.0.3 on 2024-04-04 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking_app', '0004_remove_loggedhours_department_loggedhours_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedhours',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetracking_app.department'),
        ),
    ]
