# Generated by Django 5.0.3 on 2024-04-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking_app', '0005_alter_loggedhours_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedhours',
            name='department',
        ),
    ]
