# Generated by Django 5.0.3 on 2024-04-08 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking_app', '0008_alter_loggedhours_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedhours',
            name='employee',
        ),
        migrations.AddField(
            model_name='loggedhours',
            name='employee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
